World Happiness Report

Data Description

The happiness scores and rankings use data from the Gallup World Poll. The scores are based on answers to the main life evaluation question asked in the poll. This question, known as the Cantril ladder, asks respondents to think of a ladder with the best possible life for them being a 10 and the worst possible life being a 0 and to rate their own current lives on that scale. The scores are from nationally representative samples for the years 2013-2016 and use the Gallup weights to make the estimates representative. The columns following the happiness score estimate the extent to which each of six factors – economic production, social support, life expectancy, freedom, absence of corruption, and generosity – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country that has values equal to the world’s lowest national averages for each of the six factors. They have no impact on the total score reported for each country, but they do explain why some countries rank higher than others.

Importing required libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 
from sklearn import linear_model,datasets
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/happiness_score_dataset.csv')
df

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [9]:
df.shape

(158, 12)

In [10]:
df.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [14]:
df.isnull().sum()

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [15]:
df.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [25]:
new_df=df.drop(['Country','Happiness Rank','Region'],axis=1)
new_df

,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...
153,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [26]:
feature=new_df.drop('Happiness Score',axis=1)
target=df['Happiness Score']
reg=linear_model.LinearRegression()
new_df.head()

,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [27]:
from sklearn.linear_model import LinearRegression
x=new_df.drop('Happiness Score',axis=1)
lm=LinearRegression()
lm.fit(x,new_df['Happiness Score'])

LinearRegression()

In [28]:
print('Estimated Intercept is',lm.intercept_)

Estimated Intercept is 7.401141772600539e-05

In [29]:
print('The number of coefficients in this model are',lm.coef_)

The number of coefficients in this model are [-1.75982878e-04  1.00010232e+00  9.99970526e-01  9.99877780e-01
  9.99695750e-01  9.99915961e-01  1.00006100e+00  1.00003081e+00]

In [30]:
coeff=zip(x.columns,lm.coef_)
coe=pd.DataFrame(list(zip(x.columns,lm.coef_)),columns=['features','coefficients'])
coe

                        features  coefficients
0                 Standard Error     -0.000176
1       Economy (GDP per Capita)      1.000102
2                         Family      0.999971
3       Health (Life Expectancy)      0.999878
4                        Freedom      0.999696
5  Trust (Government Corruption)      0.999916
6                     Generosity      1.000061
7              Dystopia Residual      1.000031

In [31]:
lm.predict(x)[0:100]

array([7.58687393, 7.56086815, 7.52699615, 7.52215171, 7.42687699,
       7.40600792, 7.37809917, 7.36361297, 7.2859942 , 7.28397913,
       7.27769897, 7.22570406, 7.19980975, 7.18729964, 7.11950016,
       6.98257107, 6.94617825, 6.94021123, 6.9373352 , 6.90131913,
       6.86719525, 6.85292821, 6.8102164 , 6.79772833, 6.78623143,
       6.75011631, 6.6696767 , 6.61123583, 6.57503675, 6.57405107,
       6.50507421, 6.48510122, 6.47677041, 6.45467371, 6.41114035,
       6.32891961, 6.30240062, 6.2981499 , 6.29475955, 6.26924898,
       6.16768713, 6.13015671, 6.12277924, 6.00271517, 5.99509226,
       5.98705183, 5.98374999, 5.97522064, 5.95964277, 5.94818723,
       5.88973648, 5.88900996, 5.87831189, 5.85520207, 5.84765038,
       5.83265937, 5.82827432, 5.82411781, 5.81251728, 5.79059128,
       5.77040957, 5.75860463, 5.75438653, 5.71586271, 5.70884392,
       5.69528734, 5.68873658, 5.60463202, 5.58863928, 5.5481399 ,
       5.47702907, 5.47377359, 5.42855893, 5.39872122, 5.36026355,
       5.33248751, 5.28635359, 5.26798526, 5.25281934, 5.21194716,
       5.19378391, 5.1922911 , 5.19234614, 5.14041579, 5.12888034,
       5.1241797 , 5.12312915, 5.10166352, 5.09757441, 5.07327461,
       5.05724121, 5.01309572, 5.00704005, 4.97112812, 4.95936509,
       4.94874364, 4.89755487, 4.88448947, 4.87600139, 4.87424774])

In [34]:
m=np.mean((df['Happiness Score']-lm.predict(x))**2)
print(m)

7.554105811038708e-08

In [ ]:
lm2=LinearRegression()
lm2.fit(x[['Family']],df.Happiness_Score)